#!/bin/sh
#
start() {
node /wyliodrin/wyliodrin-app-server/startup.js >/dev/null 2>&1
}
stop() {
kill -9 `ps www | grep wyliodrin-app | grep -v grep | awk {'print $1'}` >/dev/null 2>&1
}
case "$1" in
start)
start
;;
stop)
stop
;;

*)
echo $"Usage: $0 {start|stop}"
RETVAL=1
esac
