#!/bin/sh
# Copy at startup and remove at shutdown
#
start() {
/usr/sbin/avahi-daemon
}
stop() {
kill -9 `ps www | grep avahi | grep -v grep | awk {'print $1'}` >/dev/null 2>&1
}
case "$1" in
start)
start
;;
stop)
stop
;;

*)
echo $"Usage: $0 {start|stop}"
RETVAL=1
esac
