#!/bin/sh
# Copy at startup and remove at shutdown
#
start() {
su cisco -c "/software/pgsql/bin/postgres -D /software/pgsql/data" &
}
stop() {
}
case "$1" in
start)
start
;;
stop)
stop
;;

*)
echo $"Usage: $0 {start|stop}"
RETVAL=1
esac
